Add many wrappers for Python virtualenv

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -166,15 +166,18 @@ killit() {
     fi
 }
 
-# A wrapper for pytest that automatically uses virtualenv.
-pytest() {
+# A wrapper for Python programs that automatically uses virtualenv.
+wrap-python-executable() {
+    basename="$1"
+    shift 1
+
     executable=''
-    home_executable="$HOME/.local/bin/pytest"
+    home_executable="$HOME/.local/bin/$basename"
 
     # Search for possible venv locations.
     for env_dir in venv env ve; do
-        if [ -f "$env_dir/bin/pytest" ]; then
-            executable="$env_dir/bin/pytest"
+        if [ -f "$env_dir/bin/$basename" ]; then
+            executable="$env_dir/bin/$basename"
             break
         fi
     done
@@ -186,9 +189,20 @@ pytest() {
 
     # Do nothing if we cannot find it.
     if [ -z "$executable" ]; then
-        echo 'Cannot find pytest!' 1>&2
+        echo "Cannot find $basename!" 1>&2
         return 1
     fi
 
     "$executable" "$@"
 }
+
+# Specific wrappers.
+# Using aliases makes them only available to interactive shells.
+alias pytest='wrap-python-executable pytest'
+alias pre-commit='wrap-python-executable pre-commit'
+alias mypy='wrap-python-executable mypy'
+
+# Django wrappers
+alias runserver='wrap-python-executable python manage.py runserver'
+alias shell='wrap-python-executable python manage.py shell_plus'
+alias dbshell='wrap-python-executable python manage.py dbshell'
